### ISSUE TITLE
Invert the meaning of HAS_CXX_WFORMAT

### ISSUE THREAD

**Issue by loqs** [gogglesmm/gogglesmm#105]
HAS_CXX_WFORMAT originally tested and set `-Wformat=2` [1].  It was changed to `-Wno-format` in [2].  This breaks the use of CXX_FLAGS containing `-Wformat -Werror=format-security` as CXXFLAGS are placed before the options from the CMakeLists.txt -Wno-format comes after and cancels -Wformat this causes -Werror=format-security to cause a compilation failure
```
cc1plus: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
```
Could it be changed back to `-Wformat=2` or the weaker `-Wformat`?  I tested building with gcc 11.2.1 with the former change and 1.2.2 built without issue.

[1]: 5feb24c0b182cb0831c9260b218e89b5e2526ab8
[2]: 9497455fa7f539b60b5b1c32680c30466f394d09

**Comment by gogglesguy** [comment]
Maybe, why are you building a debug build?

**Comment by loqs** [comment]
No the default flags for Arch Linux are
```
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
```
https://gitlab.archlinux.org/archlinux/devtools/-/blob/master/makepkg-x86_64.conf#L43

**Comment by gogglesguy** [comment]
Ah I see now. It's part of the cfox build. The github links weren't working for me. Looks to be related newer gcc https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79677. Perhaps I can add -Wno-format-security.

**Comment by gogglesguy** [comment]
I believe current development branch no longer suffers this issue.

**Comment by gogglesguy** [comment]
1.2.3 should build again.
