### ISSUE TITLE
Doesn't work internet-radio from develop branch. Unable to open http://any

### ISSUE THREAD

**Issue by 4fury-c3440d8** [gogglesmm/gogglesmm#108]
I get gogglesmm sources from develop branch and compiled it with CFOX=ON and CFOX=OFF.   
System version of libfox: 1.7.82

**Comment by gogglesguy** [comment]
Yes, looks like the IO changes in FOX were not properly ported over.

**Comment by 4fury-c3440d8** [comment]
Thank you for your attention! With a recent commit from develop branch internet-radio is successfully works again.
