### ISSUE TITLE
Relese 1.2.3 build fail

### ISSUE THREAD

**Issue by Pro-pra** [gogglesmm/gogglesmm#109]
```
DEBUG: Replacing occurences of FXString::compare
DEBUG: CMake Error at src/CMakeLists.txt:319 (file):
DEBUG:   file failed to open for reading (No such file or directory):
DEBUG:     /builddir/build/BUILD/gogglesmm-1.2.3/src/icons.cpp
```

cfox/lib/icons.cpp may be?

**Comment by gogglesguy** [comment]
Workaround is either compile with CFOX or upgrade FOX to > 1.7.80.

**Comment by gogglesguy** [comment]
I put a fix in the develop branch if you like to see if that works:
https://github.com/gogglesmm/gogglesmm/compare/master...develop

**Comment by Pro-pra** [comment]
thank you for fix. in my build i manual copy cfox/lib/icons.cpp to src/icons.cpp :))
