### ISSUE TITLE
cannot play radio

### ISSUE THREAD

**Issue by nerijus** [gogglesmm/gogglesmm#11]
Cannot play any radio station. For example, http://sfstream1.somafm.com:8302. I get an error dialog box: Unable to open http...

**Comment by nerijus** [comment]
If I try to play http://ice.somafm.com/doomed-64.aac radio station, gogglesmm displays:
No reader available for aac format.
cmake does find FAAD libraries.

**Comment by gogglesguy** [comment]
version?

**Comment by nerijus** [comment]
1.0.18

**Comment by gogglesguy** [comment]
Ok, I think I messed up both buildsystems for AAC. Those will be fixed soon, however your stream still won't play. Some decoding issue that will require further investigation.

**Comment by nerijus** [comment]
Just FYI, 1.1.0 says "Fatal decoder error".

**Comment by gogglesguy** [comment]
Yeah, I haven't been able to address the decoding issue. Do you know by any chance which version it stopped working for you?

**Comment by nerijus** [comment]
1.0.5 works, 1.0.6 does not.

**Comment by gogglesguy** [comment]
Thanks, I see 1.0.5 just simply ignored all decoder errors.

**Comment by nerijus** [comment]
https://github.com/gogglesmm/gogglesmm/commit/0d747320ec8cc918e02c6d64a861928ce8a4af91 if I apply this patch to 1.0.5, it stops playing that stream.

**Comment by gogglesguy** [comment]
I've just pushed  a change on stable. I think this will make it work again! Mind testing?

**Comment by nerijus** [comment]
Yes, it works now, thanks!
