### ISSUE TITLE
Package for Ubuntu 23.04

### ISSUE THREAD

**Issue by LukeZBaker** [gogglesmm/gogglesmm#110]
Is there any chance of a package for Ubuntu 23.04 please?

**Comment by gogglesguy** [comment]
Yes, updates Ubuntu packages for the latest version are on my to-do list

**Comment by bornagainpenguin** [comment]
Sorry to be a pain but while working on something for 23.04, is there any chance those of us on 22.04 LTS could see a release?

I tried to install an older version manually but it complained about libssl1.1 (>=1.1.0) dependencies and I don't like to play around with libssl....encryption is not something I play fast and loose with.  Apparently the current LTS is using libssl3 now?

In any case thank you for your time and the project. It looks to be exactly what I have been looking for on Linux.

**Comment by gogglesguy** [comment]
Bionic and Jammy packages have been uploaded. Try them out and let me know if you see any issues. Other Ubuntu releases, if still supported by launchpad will follow.

**Comment by bornagainpenguin** [comment]
Thank you so very much! Liking the app with one exception (which is probably a misunderstanding of something on my part) is there no genre field that can be displayed in the columns?  Thank you again, very much!

**Comment by gogglesguy** [comment]
> Thank you so very much! Liking the app with one exception (which is probably a misunderstanding of something on my part) is there no genre field that can be displayed in the columns? Thank you again, very much!

I suppose it is kind of hidden Ctrl-T will show the Tag / Genre list.

**Comment by gogglesguy** [comment]
> Ah! That's definitely a part of it. I didn't put together that tags = genres. I have it now. Thanks!
> 
> Is there any documentation I can read for the app?

No, only the man page

**Comment by bornagainpenguin** [comment]
**Try them out and let me know if you see any issues.**

You said to mention them so I will but I'll be starting a new thread since this one is closed.
