### ISSUE TITLE
Theme resets every time opened

### ISSUE THREAD

**Issue by bornagainpenguin** [gogglesmm/gogglesmm#112]
When I open the music app it looks like this:

![Screenshot at 2023-06-09 16-01-51](https://github.com/gogglesmm/gogglesmm/assets/82099949/4fc314e9-5063-48bf-b384-295fbfa8fc86)

No big deal, I'll just change things in the settings, right?

![Screenshot at 2023-06-09 16-02-02](https://github.com/gogglesmm/gogglesmm/assets/82099949/f66f0b66-a144-47d8-99af-f00498fc4d0a)

The problem is that when I open it again the theme has reverted for me.

I am running Ubuntu-Mate 22.04.2 LTS, with Mate desktop 1.26.0. It is possible I am missing something as far as themes installed are concerned and I'd be happy to check that and install as needed but I don't understand why it is not remembering that the theming has been set and reverting it each time I launch.

**Comment by gogglesguy** [comment]
Yeah, It's a bug i only recently discovered.

**Comment by bornagainpenguin** [comment]
I see.

Another issue (I can start a new thread if needed) I discovered is that importing music to the library does not seem to actually move the music.  Is there a setting I am missing here or is this intended behavior?

**Comment by sanderjansen** [comment]
> I see.
> 
> Another issue (I can start a new thread if needed) I discovered is that importing music to the library does not seem to actually move the music. Is there a setting I am missing here or is this intended behavior?

For general questions, please use the discussion forums. 

gogglesmm does not move your music by the design. Personally I'd be very upset if I ran some random program and it started automatically moving or renaming my carefully constructed directory tree (like photo managers).

Through editing track settings, it can update/renamed your music files if you so desire, but the program is very conservative and you will have to give it permission to do so.

**Comment by gogglesguy** [comment]
> I see.
> 
> Another issue (I can start a new thread if needed) I discovered is that importing music to the library does not seem to actually move the music. Is there a setting I am missing here or is this intended behavior?

For general questions, please use the discussion forums.

gogglesmm does not move your music by the design. Personally I'd be very upset if I ran some random program and it started automatically moving or renaming my carefully constructed directory tree (like photo managers).

Through editing track settings, it can update/renamed your music files if you so desire, but the program is very conservative and you will have to give it permission to do so.

**Comment by gogglesguy** [comment]
Fix in develop (9ece92a211bfd3a9d0c9febf7f95e4459db3539d)

**Comment by gogglesguy** [comment]
Fixed in 1.2.4
