### ISSUE TITLE
[BUG] Crash on Arch Linux

### ISSUE THREAD

**Issue by thealio** [gogglesmm/gogglesmm#115]
Hi
when I try to add or sync a folder or a file ,  the player just crash , with a segmentation error and core dump creted
I'm on Arch Linux

**Comment by 42nribeiro** [comment]
same here. arch linux. segmentation error.

**Comment by gogglesguy** [comment]
gogglesmm is currently not taglib2 compatible. The [patch](https://gitlab.archlinux.org/archlinux/packaging/packages/gogglesmm/-/blob/main/taglib-2.patch?ref_type=heads) provided by Arch Linux maintainer is itself broken. Recommend to use taglib 1.13 for the time being.

**Comment by gogglesguy** [comment]
Fixed in https://github.com/gogglesmm/gogglesmm/releases/tag/1.2.5
