### ISSUE TITLE
Random segfault after a song ends

### ISSUE THREAD

**Issue by jlneder** [gogglesmm/gogglesmm#26]
I keep getting segfaults after gogglesmm ends playing a song and (i suppose) try to look for the next. It occurs at random not always. I really don't have any clue about what's causing this. I have 6 core dumps and counting if there are of any use. Is not happening too often to be a real issue but nevertheless it would be nice to left it running without supervision.
I was hoping you could tell me if there is a way to compile it with "debug" flags and have more info to put in here.
The version i'm using is gogglesmm-0.14.2 from archlinux x86_64

**Comment by elasmo** [comment]
I'm experiencing similar problems, though not specifically related to the switch between tracks.
Using gogglesmm-v0.14.2 and Linux hoki 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux.
Let me know if you need any detailed info. gdb generates a huge >100MB core dump.

(...)
src/gap/ap_output_thread.cpp:263: FXASSERT(delay<position) failed.
[player] bos
[player] meta

Program received signal SIGSEGV, Segmentation fault.
GMWindow::updateCover (this=this@entry=0x9e4da0) at src/GMWindow.cpp:1308
(...)

**Comment by gogglesguy** [comment]
Interesting, looks like it may be related to the failure of reading a cover. Is it reproducible? If you play the same track does it crash again?

**Comment by elasmo** [comment]
Yes it's reproducible.

**Comment by gogglesguy** [comment]
A fix is on the develop branch.

**Comment by elasmo** [comment]
I will try it out later when I have got the time.
Thanks!

**Comment by elasmo** [comment]
So far I haven't experienced any problems with the develop branch. Good stuff, thanks!

**Comment by gogglesguy** [comment]
Thanks for testing and the report!
