### ISSUE TITLE
crash (TagLib: A picture frame must contain at least 5 bytes)

### ISSUE THREAD

**Issue by nerijus** [gogglesmm/gogglesmm#29]
gogglesmm crashes when playing http://sat.lt/test.mp3 : 
TagLib: A picture frame must contain at least 5 bytes.
Segfault

[backtrace.log | uploaded via ZenHub](https://files.zenhub.io/55103fd26055ee4626435d73)

**Comment by gogglesguy** [comment]
Thanks for the report!
