### ISSUE TITLE
Editing a songs attributes leads to strange effects 

### ISSUE THREAD

**Issue by dwerner1** [gogglesmm/gogglesmm#30]
Hi,
I have just edited a (playing) music file's attributes - that made the files rating, as shown in the attached image, explode!
Goggles is cool! 
Best regards
Dirk

![goggles](https://cloud.githubusercontent.com/assets/6715683/8396418/6e842e7c-1da4-11e5-9ad6-b248de48f392.png)

**Comment by dwerner1** [comment]
Sorry, forgot to mention the version - it's v.0.14.2 on debian 8

**Comment by gogglesguy** [comment]
Thanks for the report. Looks like a small minor issue.

**Comment by gogglesguy** [comment]
Fixed in v1.0.5
