### ISSUE TITLE
Import playlist not working in gogglesmm 1.0.7

### ISSUE THREAD

**Issue by dwerner1** [gogglesmm/gogglesmm#35]
Importing a playlist in gogglesmm 1.0.7, that had been created with gogglesmm 1.0.1 and saved as xspf  file has no effect

**Comment by gogglesguy** [comment]
Looks like the locations (urls) stored in the xspf file are being double encoded. Since FOX-1.7.17 the FXURL::fileToURL started to encode characters itself. Nice catch!
