### ISSUE TITLE
Title tag in .flac files ripped with grip is "ignored". Tracks show up as "Untitled" 

### ISSUE THREAD

**Issue by sophom** [gogglesmm/gogglesmm#36]
I've started re-ripping my favourites from my CD collection in flac using grip and I noticed that now all the track (song titles) in all my freshly ripped flac files show up as "Untitled". This is just the title tag... all the other tags (track, year, artist, album artist, album) in the same .flac file are read properly. The title tags in these same flac files are parsed correctly by easytag, Rhythmbox and Nightingale. 

All that being said on flac files that I downloaded from humblebundle, all tags, including the title tag, are parsed correctly by gmm.

Right now I'm using the gmm 1.08 from git yesterday although this happens with earlier versions as well.

**Comment by nerijus** [comment]
You should probably post a link to a test flac file.

**Comment by gogglesguy** [comment]
As @nerijus said, a sample file would be greatly appreciated.

**Comment by gogglesguy** [comment]
This occurs when the flac file has an ID3v2 or ID3v1 tag (written by Grip) in addition to an xiphcomment block (written by the flac encoder). We do some special processing in case for titles in xiph comments  and incorrectly assume when a xiph comment block is available it also contains  any metadata and stop reading any other tags in the file.

**Comment by gogglesguy** [comment]
A fix is in stable. Please try it out and let me know if you encounter any issues.

**Comment by sophom** [comment]
Yes. That fixed it! In less than 24 hours and without a failing case. Impressive!

I didn't really have any issues except I couldn't figure out how to get gmm to re-read my existing collection. Basically any new flac file I added, that was not already in the db, had the title correctly parsed but all the old ones stayed with "Untitled" as a title. I then deleted the .goggles directory in my home directory which had no effect. I guess that was the location for the older versions of gmm. After a few moments of confusion and disbelief I used the source, found the --enable-debug and got a nice printf of the location of the db (.local this time). After I deleted just the db I then restarted gmm and all the titles in my flac files are correct. I double checked a bunch of them. I'm happy now. BTW I'm very happy with how fast it goes through my entire collection to create the db.

**Comment by gogglesguy** [comment]
I'm glad it works! You definitely took the 'long' option of clearing the database. There's the right-click menu option on the Music Library item to clear the database. Also the "Sync Folder" has an option to force rereading any files or simply remove files from the database that are in that specific folder.

The .goggles was indeed from an older version of gogglesmm. We now use the XDG spec for our storage locations. The various locations are described in the man page included with gogglesmm.

Deleting the database file is of course an option but if you use the podcast manager, you'll lose those as well.

**Comment by sophom** [comment]
Yeah... That was a brute force method and should have explored the various tabs in sync a little more. While I don't have any podcasts there, I did lose all my internet radio stations which kind of sucked as I had manually entered them. Luckily I was able to restore them from backup.
