### ISSUE TITLE
Stop playing after some time

### ISSUE THREAD

**Issue by nerijus** [gogglesmm/gogglesmm#37]
It would be nice to have this functionality, for example, before going to sleep I would select to stop playing after 30 minutes. Or it could be another play button which would play for specified time and then stop. It would be nice to have this functionality by MPRIS, but I am not sure if it's possible.

**Comment by gogglesguy** [comment]
There's the "Sleep Timer" which I believe should still exist and still be in working order (fingers crossed). Can be found in the media control menu next to the volume control.

**Comment by nerijus** [comment]
Yes, it exists, thank you. Do you know if it's possible to use it by MPRIS (kdeconnect)?

**Comment by gogglesguy** [comment]
No. MPRIS is merely an interface specification (http://specifications.freedesktop.org/mpris-spec/latest/) and there's no "Sleep Timer" call in that spec. Even exposing this as an additional method would not be helpful unless the clients knows how to call this. Once you start thinking about modifying the client, you may as well just set a timer in the client itself and call the appropriate stop() method of whatever MPRIS capable player is currently running when that timer expires.
