### ISSUE TITLE
Menu "frame" size does not adapt to larger font sizes

### ISSUE THREAD

**Issue by sophom** [gogglesmm/gogglesmm#38]
While trying to make gogglesmm look more native on my xfce desktop I tried changing the fonts to "droid, sans 10" and the last menu entry (Quit) got cropped (see attached). I believe this used to work in the older versions of gmm (.7? era). If I increase the size to 11, the last menu entry is not at all visible.

![gmm_menu_cropped](https://cloud.githubusercontent.com/assets/11645950/12088896/4915d49e-b2ad-11e5-8b00-8fa1c269739e.png)

This problem occurs with the other menus as well.

**Comment by gogglesguy** [comment]
Restarting the application after changing the fontsize will fix the issue.

**Comment by gogglesguy** [comment]
Fixed in 43cab35

**Comment by sophom** [comment]
Perfect! I tried both larger fonts and smaller ones and it resizes appropriately immediately with no need to restart.  I also noticed that the shortcuts don't get clobbered by the menu entry text any more. Happy camper here!

**Comment by sophom** [comment]
I should have closed this when I made my previous comment

**Comment by gogglesguy** [comment]
I actually prefer to close them when they've been officially released. :)

**Comment by gogglesguy** [comment]
Available in https://github.com/gogglesmm/gogglesmm/releases/tag/1.0.10
