### ISSUE TITLE
Album grouping by directory (force)

### ISSUE THREAD

**Issue by gogglesguy** [gogglesmm/gogglesmm#42]
Add a new import option to help importing compilation albums that don't have the ALBUM_ARTIST tag set and may have different ARTIST tags but still need to be grouped under the same album. See #39 discussion as well.

**Comment by gogglesguy** [comment]
Available in https://github.com/gogglesmm/gogglesmm/releases/tag/1.0.10

**Comment by sophom** [comment]
This works well. Thank you! I went from 580+ to 557 albums.
