### ISSUE TITLE
Sync should remove files from database that match exclude filter

### ISSUE THREAD

**Issue by gogglesguy** [gogglesmm/gogglesmm#43]
Either as an additional sync operation or enabled by default for all operations.
See Issue #41.

**Comment by gogglesguy** [comment]
Just committed the initial implementation on https://github.com/gogglesmm/gogglesmm/tree/stable. It should remove all matching files/folders in the exclude filters on any of the operations (import / update / remove missing / remove folder). 

Let me know if you notice any issues.

**Comment by nerijus** [comment]
Thank you very much, now it's perfect!

**Comment by gogglesguy** [comment]
Thanks for testing!

**Comment by gogglesguy** [comment]
I'm thinking of removing the "Remove tracks found in folder from database" from the Sync Folder functionality and make this a separate "Remove Folder" menu option (probably as a right click menu option of the Music Library item in the sources list) instead. 

The exclude filter we currently have for import and sync doesn't really work for the Remove Folder, so by making it a separate function we can easily remove the filter from that dialog.

So we're not removing functionality, just grouping it more logically. I think both the sync and remove folder will end up easier and perhaps less overwhelming to use.

Thoughts @nerijus ?

**Comment by nerijus** [comment]
Yes, I think "Remove tracks found in folder from database" can be removed, as it is a bit confusing now.
But I'd like to have both functionalities - Exclude Filter as it is now, and the new right click menu option for removing items (because removed items may be nested deep).

**Comment by gogglesguy** [comment]
The exclude filter will stay in Sync Folder and anything matching the filter will not be imported, updated and will automatically get removed from the database (as you requested).

But for Remove Folder, what should the Exclude Filter's behavior be? If it is using the same behavior as Sync Folder, it becomes a no-op since we already remove every file in that folder. Instead, if is using the old behavior, it would remove all files from that folder except for the ones that match the filter. Are you advocating for the latter?

**Comment by nerijus** [comment]
It would be probably easiest if Remove Folder would not have Exclude Filter at all, or it would be the same as Sync Folder, i.e. no-op.
