### ISSUE TITLE
Make use of xdg-icon-resource for non-package installs if available.

### ISSUE THREAD

**Issue by sophom** [gogglesmm/gogglesmm#44]
I installed gogglesmm from source (github yesterday after the major update) on my wifes computer that had a clean installation of xubuntu14.04. When I say a clean installation, I mean one that never had the version of gogglesmm from the ubuntu repos. 

After I installed it, I noticed that the gogglesmm icon does not get used for the app either in the menus or as desktop shortcut. Looking at the desktop shortcut, I did notice that it is referring to the gogglesmm icon. I looked at this on both my computer and hers and they are both the same.

On my wifes computer, when bringing up properties on the desktop shortcut and searching all icons for gogglesmm it can't find anything. On my computer, if I do the same it does find gogglemm. 

I'll try and do some more research later. If you want me to try something let me know.

**Comment by gogglesguy** [comment]
Try running this to update the icon cache:
> sudo xdg-icon-resource forceupdate --theme hicolor

In addition you may also need this for mimetype database to be updated:
> sudo update-desktop-database -q

**Comment by gogglesguy** [comment]
Also make sure you update to 1.0.12. (1.0.11 and 1.0.10 had some bad bugs).

**Comment by sophom** [comment]
`sudo xdg-icon-resource forceupdate --theme hicolor`

Did the trick. Maybe you can add it to the faq? or maybe the makefile itself? 

Thank you!
