### ISSUE TITLE
Album Artist

### ISSUE THREAD

**Issue by nerijus** [gogglesmm/gogglesmm#46]
I have a file with an Artist ID3 tag, but empty Album Artist tag. gogglesmm displays 
Album Artist as a previous directory name. Is it possible to use Artist tag in such case?
I deselected "Group albums by audio format", didn't help.

**Comment by gogglesguy** [comment]
You may have to turn off parse by filename and use parse by tag only during import/sync

**Comment by nerijus** [comment]
I don't want to turn off parse by filename because there are no tags at all in some files.

**Comment by gogglesguy** [comment]
You could change the filename pattern to not scan for Album Artist but only for Artist. Use %p instead %P.

**Comment by nerijus** [comment]
Thanks, it works.
