### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by nerijus** [gogglesmm/gogglesmm#51]
Latest fox and gogglesmm, using cmake, fails when linking:

[ 47%] Linking CXX executable gogglesmm
cd /home/nerijus/rpmbuild/BUILD/gogglesmm-1.0.14/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/gogglesmm.dir/link.txt --verbose=1
/usr/lib64/ccache/c++   -Os -DNDEBUG  -Wl,--export-dynamic CMakeFiles/gogglesmm.dir/GMAbout.cpp.o CMakeFiles/gogglesmm.dir/GMAnimImage.cpp.o CMakeFiles/gogglesmm.dir/GMApp.cpp.o CMakeFiles/gogglesmm.dir/GMAudioPlayer.cpp.o CMakeFiles/gogglesmm.dir/GMAudioScrobbler.cpp.o CMakeFiles/gogglesmm.dir/GMAlbumList.cpp.o CMakeFiles/gogglesmm.dir/GMClipboard.cpp.o CMakeFiles/gogglesmm.dir/GMColumnDialog.cpp.o CMakeFiles/gogglesmm.dir/GMCover.cpp.o CMakeFiles/gogglesmm.dir/GMCoverCache.cpp.o CMakeFiles/gogglesmm.dir/GMCoverManager.cpp.o CMakeFiles/gogglesmm.dir/GMDatabase.cpp.o CMakeFiles/gogglesmm.dir/GMDatabaseSource.cpp.o CMakeFiles/gogglesmm.dir/GMFilename.cpp.o CMakeFiles/gogglesmm.dir/GMFilter.cpp.o CMakeFiles/gogglesmm.dir/GMFilterEditor.cpp.o CMakeFiles/gogglesmm.dir/GMFilterSource.cpp.o CMakeFiles/gogglesmm.dir/GMFontDialog.cpp.o CMakeFiles/gogglesmm.dir/GMIconTheme.cpp.o CMakeFiles/gogglesmm.dir/GMImportDialog.cpp.o CMakeFiles/gogglesmm.dir/GMImageView.cpp.o CMakeFiles/gogglesmm.dir/GMList.cpp.o CMakeFiles/gogglesmm.dir/GMLocalSource.cpp.o CMakeFiles/gogglesmm.dir/GMPlayerManager.cpp.o CMakeFiles/gogglesmm.dir/GMPlayListSource.cpp.o CMakeFiles/gogglesmm.dir/GMPlayQueue.cpp.o CMakeFiles/gogglesmm.dir/GMPodcastSource.cpp.o CMakeFiles/gogglesmm.dir/GMPreferences.cpp.o CMakeFiles/gogglesmm.dir/GMPreferencesDialog.cpp.o CMakeFiles/gogglesmm.dir/GMPresenter.cpp.o CMakeFiles/gogglesmm.dir/GMRemote.cpp.o CMakeFiles/gogglesmm.dir/GMSession.cpp.o CMakeFiles/gogglesmm.dir/GMScanner.cpp.o CMakeFiles/gogglesmm.dir/GMSource.cpp.o CMakeFiles/gogglesmm.dir/GMSourceView.cpp.o CMakeFiles/gogglesmm.dir/GMTag.cpp.o CMakeFiles/gogglesmm.dir/GMTaskManager.cpp.o CMakeFiles/gogglesmm.dir/GMTrack.cpp.o CMakeFiles/gogglesmm.dir/GMTrackDatabase.cpp.o CMakeFiles/gogglesmm.dir/GMTrackEditor.cpp.o CMakeFiles/gogglesmm.dir/GMTrackList.cpp.o CMakeFiles/gogglesmm.dir/GMTrackItem.cpp.o CMakeFiles/gogglesmm.dir/GMTrackView.cpp.o CMakeFiles/gogglesmm.dir/GMTrayIcon.cpp.o CMakeFiles/gogglesmm.dir/GMStreamSource.cpp.o CMakeFiles/gogglesmm.dir/GMWindow.cpp.o CMakeFiles/gogglesmm.dir/main.cpp.o CMakeFiles/gogglesmm.dir/icons.cpp.o CMakeFiles/gogglesmm.dir/fxext.cpp.o CMakeFiles/gogglesmm.dir/gmutils.cpp.o CMakeFiles/gogglesmm.dir/GMDBus.cpp.o CMakeFiles/gogglesmm.dir/GMSettingsDaemon.cpp.o CMakeFiles/gogglesmm.dir/GMMediaPlayerService.cpp.o CMakeFiles/gogglesmm.dir/GMNotifyDaemon.cpp.o CMakeFiles/gogglesmm.dir/GMAppStatusNotify.cpp.o  -o gogglesmm  -flto gap/libgap.a -lFOX-1.7 -lsqlite3 -ltag -ldbus-1 -lGLU -lGL -lGLEW -lGLU -lGL -lX11 -lSM -lICE /usr/lib64/libgcrypt.so -flto /usr/lib64/libexpat.so -lFLAC -lvorbis -logg -lopus /usr/lib64/libmad.so /usr/lib64/libfaad.so -lGLEW -lX11 -lSM -lICE /usr/lib64/libgcrypt.so 
/tmp/ccTRAlRN.ltrans0.ltrans.o: In function `GMAudioPlayer::manufacture()':
<artificial>:(.text+0xb02): undefined reference to `ap::AudioPlayer::AudioPlayer()'
/tmp/ccTRAlRN.ltrans0.ltrans.o: In function `GMAudioScrobbler::run()':
<artificial>:(.text+0x2627): undefined reference to `ap::ap_set_thread_name(char const*)'
<artificial>:(.text+0x2893): undefined reference to `ap::XmlParser::parse(FX::FXString const&, FX::FXString const&)'
<artificial>:(.text+0x2c15): undefined reference to `ap::HttpClient::HttpClient(ap::ConnectionFactory*)'
<artificial>:(.text+0x2c73): undefined reference to `ap::HttpClient::basic(char const*, FX::FXString, FX::FXString const&, FX::FXString const&, FX::FXString*)'

**Comment by gogglesguy** [comment]
You mind sending me the complete build log, including the cmake invocation (from a fresh unzipped tarball please).

**Comment by gogglesguy** [comment]
Try commenting out:
 
CHECK_CXX_COMPILER_FLAG(-flto       HAS_CXX_OPTIMIZE_LINKTIME)

Rerun cmake and make.

**Comment by nerijus** [comment]
Removing CHECK_CXX_COMPILER_FLAG(-flto HAS_CXX_OPTIMIZE_LINKTIME) helped.

**Comment by gogglesguy** [comment]
Please leave further comments at #54
