### ISSUE TITLE
Gogglesmm linking fails with many undefined reference errors to FX library

### ISSUE THREAD

**Issue by GvMariani** [gogglesmm/gogglesmm#52]
Trying to build gogglesmm 1.0.14 on Rosa Linux 2014.1 x86_64, using cmake.
The build fails at around 46% with a botload of undefined references to various FX functions (see attached log).:
The issue was present also with the configure-based build and putting an 
export LDFLAGS="-lFOX-1.7" before configure&make, solves it (but the build fails later: see next report).
[BuildingError.txt](https://github.com/gogglesmm/gogglesmm/files/311872/BuildingError.txt)

**Comment by gogglesguy** [comment]
Don't build with -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF. That build path isn't totally fleshed out yet. Don't build shared libraries: -DBUILD_SHARED_LIBS:BOOL=OFF

**Comment by gogglesguy** [comment]
Please add comments to #54
