### ISSUE TITLE
Gogglesmm linking fails with many undefined reference errors

### ISSUE THREAD

**Issue by GvMariani** [gogglesmm/gogglesmm#53]
Trying to build gogglesmm 1.0.14 on Rosa Linux 2014.1 x86_64, using cmake.
After working around the issue described in the report #52, the build still fails when linking the gogglesmm executable (see attached log). The undefined reference errors are related to an unknown (to me) "ap" namespace...
When using the old configure, instead of the recommended cmake, the build is successful.
[LinkingError.txt](https://github.com/gogglesmm/gogglesmm/files/311897/LinkingError.txt)

**Comment by gogglesguy** [comment]
Try commenting out in CMakeLists.txt:

CHECK_CXX_COMPILER_FLAG(-flto HAS_CXX_OPTIMIZE_LINKTIME)

Rerun cmake and make.

**Comment by gogglesguy** [comment]
Please add comments to #54
