### ISSUE TITLE
cmake build system

### ISSUE THREAD

**Issue by gogglesguy** [gogglesmm/gogglesmm#54]
Improvements to be made to cmake build system in regards to #51, #52, and  #53 

- [x] Fix shared library build of libgap
- [x] libgap when build as shared library should link to FOX.
- [x] CMAKE_INSTALL_LIBDIR should be usable as relative and absolute path
- [x] Install GAP plugins in correct LIBDIR.
- [x] Disable -lto compilation.

**Comment by GvMariani** [comment]
Sorry for my delayed reply: I was a bit busy in the last two days...

> Don't build with -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF. That build path isn't totally fleshed out yet. Don't build shared libraries: -DBUILD_SHARED_LIBS:BOOL=OFF
Yep, but I don't have a lot of choice here: the above are the default for a build in Rosa Linux...
Anyway, the configure way still works ok, so I raised the issue only to aid in completing the cmake support...

> Try commenting out in CMakeLists.txt:
> CHECK_CXX_COMPILER_FLAG(-flto HAS_CXX_OPTIMIZE_LINKTIME)
> Rerun cmake and make
Sorry this one alone does not work... see attached log
[LinkingError2.txt](https://github.com/gogglesmm/gogglesmm/files/316696/LinkingError2.txt)

Setting also -DBUILD_SHARED_LIBS:BOOL=OFF makes the linking error with gogglesmm executable go away, but then fails the install phase:
*************
make DESTDIR=/tmp/abf/rpmbuild/BUILDROOT/gogglesmm-1.0.14-1-rosa2014.1.x86_64-buildroot install
Makefile:12: *** No configuration found. Run ./configure first.  Stop.
*************

**Comment by GvMariani** [comment]
Arg. Scrap the last error: wrong script line...
The build succeds.

**Comment by gogglesguy** [comment]
Thanks for your feedback. It has been very helpful and usefull t. I think most of the issues should be resolved in the next release.  By default we'll now build a static library for gap and ignore the BUILD_SHARED_LIBS flag.

**Comment by GvMariani** [comment]
> By default we'll now build a static library for gap and ignore the BUILD_SHARED_LIBS flag.

You are the master here, however, IMO this can be only a partial step:
if gogglesmm needs internal libraries, it should also support building with BUILD_SHARED_LIBS set to reduce the executable footprint...
Perhaps in some next release, soon or later...

**Comment by gogglesguy** [comment]
> if gogglesmm needs internal libraries, it should also support building with BUILD_SHARED_LIBS set to > reduce the executable footprint...

If gap was actually used outside gogglesmm it would make sense to build it as a shared library, but since gap is strictly an internal library with no outside use, static vs shared makes no difference. Sure, you reduce the size of the executable, but at the cost of loading a additional shared library. The BUILD_SHARED_LIBS is really meant for library only projects where it is custom build either shared, static or both type of libraries.

There'll be flag to enable shared library, but its mostly for platforms where linking static libraries is a pain (aka Windows).

**Comment by gogglesguy** [comment]
Fixes available in 1.0.15
