### ISSUE TITLE
Tray Icon Invisible on KDE5

### ISSUE THREAD

**Issue by zx2c4** [gogglesmm/gogglesmm#58]
On KDE5, the tray icon is invisible:

![image](https://cloud.githubusercontent.com/assets/10643/18694207/462013d0-7fa8-11e6-9243-7270fbb1ac2a.png)

The blank space there is where it usually is.

**Comment by gogglesguy** [comment]
Looks like some bugs in the StatusNotifier implementation of gogglesmm. Do we still need this type of tray icon in KDE considering you have the (mpris) generic media player controls right next to it (basically doing the same thing)?

**Comment by zx2c4** [comment]
Good point: the KDE MPRIS controls are widely sufficient anyway for this.

**Comment by gogglesguy** [comment]
What is your DESKTOP_SESSION environment variable set to?

**Comment by zx2c4** [comment]
zx2c4@thinkpad ~ $ echo $DESKTOP_SESSION
/usr/share/xsessions/plasma

**Comment by gogglesguy** [comment]
Thank you.
I've updated stable branch to disable the tray icon on KDE.

**Comment by gogglesguy** [comment]
Fixed in 1.1.1

**Comment by zx2c4** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=9ce01de5e22525a6026fe5e7d4f1970c7b5bcbf7

**Comment by gogglesguy** [comment]
Great! You may want to add some versioned dependencies to your ebuild though.

**Comment by zx2c4** [comment]
Any particular suggestions?

**Comment by gogglesguy** [comment]
Here's the ubuntu build I created:
http://bazaar.launchpad.net/~s.jansen/+junk/gogglesmm/view/head:/debian/control

I'd recommend checking minimum versions for cmake, fox, sqlite and taglib. Of course, if you don't check them in your ebuild, cmake will still complain about them.
