### ISSUE TITLE
FLAC Encoded Files

### ISSUE THREAD

**Issue by SndChaser** [gogglesmm/gogglesmm#61]
FLAC files won't play correctly.  Sometimes I will get one file to play, then nothing after that will play (ie, no sound output, but the status will update).  This happens with files from multiple sources, and multiple encoding levels.

Eventually, I have to close Goggles, but it appears to be stuck as I will have to force it to close.

I don't see anything in the logs indicating there is any error message.

**Comment by gogglesguy** [comment]
Is this with version 1.1.3? Does it only happen to FLAC files? Or do you experience the same with other type of encodings (mp3,ogg)? 

If you can, try building gogglesmm with debug information (cmake -DCMAKE_BUILD_TYPE=Debug .)
and post the output of the console whenever you experience the problem.

**Comment by SndChaser** [comment]
I should have clarified this in the first part of this issue.  I'm on Manjaro Linux (a spin based Arch Linux for upstream source). The version that is being supplied is 1.1.1.

It's only with FLAC files that the issue occurs (I have a large library: 23K of FLACs, 24K of mp3',s 70K of ogg's, and a few hundred wav files).  I don't have the issue with mp3's, ogg's or wav's.  And other players (cmus, moc, clementine, DeadBeef) don't have this issue.

I'll try to pull down and build the current version of goggles, but in the mean time I have an strace I just ran against goggles to see if it might help figure out what is happening.

[goggles_trace.txt](https://github.com/gogglesmm/gogglesmm/files/615354/goggles_trace.txt)

**Comment by gogglesguy** [comment]
Thanks for the additional information. I do think this was fixed in 1.1.3, so please try that version and let me know whether that fixes the problem or not.

**Comment by SndChaser** [comment]
Okay, I was able to build 1.1.3 and test it.  I wasn't able to recreate the issue I was seeing, so I believe you are correct that the issue was addressed with the 1.1.3 release.

However, I decided to throw a bit of a curve ball at the player.  I decided to try a 24bit, 48Khz encoded FLAC file.  While it is playing correctly, before it started it did throw a bunch of library assertion errors:

        stop threshold 699050 frames
[output] stream format:  48000Hz, 2ch, s24le3, (FL,FR)
[output] plugin format:  48000Hz, 2ch, s24le3, (FL,FR)
[alsa] failed to get delay Input/output error
[output] frame timer set to 0
[alsa] failed to get delay Input/output error
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
[player] bos
[player] meta
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
/home/gdb/goggles/gogglesmm/gap/ap_output_thread.cpp:254: FXASSERT(delay<position) failed.
Track Change Notification
         Title: Transformations Part One
        Artist: Cousin Silas
         Album: Transformations

I don't know if that it something you want to look into.  IMO it didn't cause a failure so I'm not worried about it.  If you need a set of those FLACs to test with, I can give you a link (it's a free, CC licensed, download from my netlabel, so there's no issue giving you a copy of it).

**Comment by gogglesguy** [comment]
Glad to hear it works. I saw that the Arch Community Repository has been updated today with 1.1.3 as well. Not sure if Manjaro has direct access to it or not.

As far as the asserts concerned, I believe it is working fine, and the assertion itself is incorrect.

**Comment by SndChaser** [comment]
Manjaro is good about rolling up the upstream updates on a weekly basis, so I'll probably have it next weekend.  I'm surprised it took that long for the Arch sponsor to roll up the new version.

BTW - wanted to say I'm quite impressed with Goggles -- I've used lots of audio managers / players, and few make the kind of impression that Goggles has: it's extremely lightweight (even uses less memory than cmus), and extremely capable (some features that some heavy weights don't have, like handling podcasts and streaming stations).  I wish more developers took your approach to developing applications.

**Comment by gogglesguy** [comment]
Thank you! I appreciate you trying it out.
