### ISSUE TITLE
Ubuntu Sound Menu Integration & GNOME shortcuts

### ISSUE THREAD

**Issue by BellaMay95** [gogglesmm/gogglesmm#62]
Is there a way to get the play/pause buttons for gogglesmm in the Ubuntu sound menu (I'm on Ubuntu 16.10)? The changelog says that the player uses mpris2 so I understand that that functionality should be available. I put the gogglesmm entry in the sound menu with `gsettings set com.canonical.indicator.sound interested-media-players "['gogglesmm]"` and it appears but without the play/pause functionality.

Also, on a related note, I see the list of keyboard shortcuts available, but is it possible to also bind the GNOME multimedia shortcuts to the program? They were working for me on version 0.12.7 but not on version 1.0.13.

**Comment by gogglesguy** [comment]
Could you try version 1.1.3 from my ppa: https://launchpad.net/~s.jansen/+archive/ubuntu/gogglesmm ?

**Comment by BellaMay95** [comment]
Version 1.1.3 fixes the two issues I was having, I can see gogglesmm in the sound menu and I can use the GNOME media shortcuts to start the player, however the only way I can view the player is clicking it open through the sound menu. Clicking the icon on the dashboard (or through the Launchpad) does nothing. If I run "gogglesmm" through the terminal it immediately returns control to the keyboard as if it does nothing. If I do "sudo gogglesmm" it asks for the sudo password and then just hangs without printing any output. Apparently it is opening the player in the background, it just won't open the window to show any GUI components unless I click on the entry in the sound menu.

**Comment by gogglesguy** [comment]
>  If I run "gogglesmm" through the terminal it immediately returns control to the keyboard as if it does nothing.

It's probably running then already. Try launching it with `gogglesmm --toggle-shown`
