### ISSUE TITLE
Mini player sound icon does not change when icon theme changed

### ISSUE THREAD

**Issue by OfficialBAMM** [gogglesmm/gogglesmm#64]
Steps to reproduce:
1. Set a different icon theme in the settings.
2. Switch to mini player
3. See that the sound icon is still the same.

Hope this makes it clear. Loving gogglesmm so far! Keep up the good work.

Side question: Is there any way to change the font of the clock(see below, my english does not provide today). If not, are there any plans to make that functionality? 

You can also see the sound icon i mean in the picture below.
![deepinscreenshot20170206195631](https://cloud.githubusercontent.com/assets/10955512/22661632/0161fce6-ec9e-11e6-819d-b8c82e7e5c99.png)

**Comment by gogglesguy** [comment]
The clock isn't technically a font but rather a custom drawn widget. I guess it could be made optional and use a regular font if it isn't desired.

**Comment by OfficialBAMM** [comment]
Yeah, that's what I thought. It was more of an question than a feature request.

**Comment by gogglesguy** [comment]
Fixed in 1.1.6
