### ISSUE TITLE
Command line option to invoke podcast scan / download

### ISSUE THREAD

**Issue by SndChaser** [gogglesmm/gogglesmm#66]
I am currently on an internet connection with very strict data cap. (250meg during the day).  During the over night hours (from 1am to 7am) the data cap. is removed.  So, I need a way to tell GogglesMM *when* to download podcasts.  The current options only allow up to a 12hr window, which would always set it off once during the daytime hours, which could potentially blow my data cap.

I can think of two options: (a) add a command line option like '--podcastdl' which I could call from cron to manually download podcasts, or (b) add the ability to specify a specific time in the podcast settings of the configuration.

Either option would do to allow the flexibility I need to download podcasts at an appropriate time.

**Comment by gogglesguy** [comment]
I like both ideas, but certainly the command line option should be easy to add in the short term.

**Comment by SndChaser** [comment]
Thank you.  Either option works well for my situation.

I wonder if there are more people that are encountering similar situations that would benefit from this feature.  These data caps still seem prevalent on Satellite internet connections, which I believe is the predominant method used by many people in remote locations. 

I will get DSL installed here as soon as I can...the main reason for the Satellite connection was DSL wasn't available until recently...  But, unfortunately, given the current situation I know it might be a few months before I can get DSL installed.

**Comment by gogglesguy** [comment]
Command line option available in 1.1.7.

**Comment by SndChaser** [comment]
On Tue, 28 Mar 2017 19:44:21 -0700
Sander Jansen <notifications@github.com> wrote:

> Command line option available in 1.1.7.
> 

Awesome!  I'll check it out when it hits the Manjaro / Arch repos.

George
