### ISSUE TITLE
Fatal Decoder Error

### ISSUE THREAD

**Issue by CryptoD** [gogglesmm/gogglesmm#70]
Once in a while music stops and a pop up window appears on the screen: "Fatal Decoder Error". 

After I click on OK I can continue playing music without any issue. Happens once every 2-3 hours maybe.

PCLinuxOS, KDE Plasma.

**Comment by gilcu3** [comment]
The same happens here with some m4a files, in some precise parts of the songs.

**Comment by gogglesguy** [comment]
@gilcu3 mind sending me the specific file that causes the issue

@cryptod if you have specific files that you know causes the issues, please send them to me.

**Comment by CryptoD** [comment]
Here mate
https://mega.nz/#F!wNoyBJ5R!TVPOLELtbh_702vkshyVEA
Happens when the song ends

**Comment by gogglesguy** [comment]
Thanks for the file. I've identified the issue, but at the same time I have noticed some other issue with the decoder as well.
