### ISSUE TITLE
how to tell cmake use my local fox not system's one

### ISSUE THREAD

**Issue by vrushali88** [gogglesmm/gogglesmm#73]
I was using gogglesmm-1.0.12 and now want to update it to the latest version 1.1.9 . In configuration script I used to pass --prefix=/path/to/local/fox (not the system one because system's fox is older than required one). But now in new cmake system how can I pass this option? The latest 1.1.9 giving configuration time error. 

Checking for module 'fox17>=1.7.50'
--   Package 'fox17', required by 'virtual:world', not found

**Comment by gogglesguy** [comment]
Try setting CMAKE_PREFIX_PATH before running cmake (eg /usr/local or whatever prefix path is used for you local FOX install).

**Comment by vrushali88** [comment]
Thanks for the quick respond. But this also doesn't help. 

I am running following steps. 

tar -xf gogglesmm-1.1.9.tar.gz
cd gogglesmm-1.1.9
tar -xf ../fox-1.7.60.tar.gz
cd fox-1.7.60
./configure CC=gcc CXX=g++ --prefix=/local/vrushali/fox
/usr/bin/make CC=gcc CXX=g++
/usr/bin/make install
cd ..
/usr/bin/cmake -DCMAKE_C_COMPILER:FILEPATH=`which gcc` -DCMAKE_CXX_COMPILER:FILEPATH=`which g++` -DCMAKE_VERBOSE_MAKEFILE=ON CMAKE_PREFIX_PATH=/local/vrushali/fox .
...
...
-- Checking for module 'fox17>=1.7.50'
--   Package 'fox17', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:412 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  gap/CMakeLists.txt:180 (pkg_check_modules)


-- Configuring incomplete, errors occurred!

**Comment by gogglesguy** [comment]
Try removing CMakeCache.txt and make sure to run cmake with: "-DCMAKE_PREFIX_PATH=<path>"
In your output you don't use the -D to pass variables to cmake.

**Comment by vrushali88** [comment]
-DCMAKE_PREFIX_PATH=/local/vrushali/fox woks. 

Thank you so much.
