### ISSUE TITLE
FOX Header (v1.7.60) / Library (v1.7.61) mismatch!

### ISSUE THREAD

**Issue by jmwatte** [gogglesmm/gogglesmm#74]
don’t know if this is the place but…
On Antergos  gogglesmm gives …
FOX Header (v1.7.60) / Library (v1.7.61) mismatch!
after updating on 20/11 …
grtz

**Comment by nerijus** [comment]
If you update FOX, you have to recompile gogglesmm. If gogglesmm is installed from your distro package, please complain to the package maintainer.

**Comment by jmwatte** [comment]
OK, thx
