### ISSUE TITLE
A Windows user who also loves Manjaro (Gnome) and Goggles

### ISSUE THREAD

**Issue by TedStone** [gogglesmm/gogglesmm#75]
I just verified that Googles launched fine on Manjaro before latest updates. Then installed all the updates available for Manjaro and now Goggles does not run at all. It does not launch at all... I am sad.

**Comment by gogglesguy** [comment]
Similar issue to #74. One of the libraries gogglesmm was updates which requires gogglesmm to be rebuilt. I filed a bug report on Arch Linux to request a new build.

**Comment by nerijus** [comment]
Actually gogglesmm runs with a newer FOX if I comment out line 67 "return 1;" in main.cpp. But  I understand, that sometimes it may crash.

**Comment by gogglesguy** [comment]
Packages were updated.
