### ISSUE TITLE
Album\Track Edit function is very, very slow and sometimes freezes system v0.12.7

### ISSUE THREAD

**Issue by ejsant** [gogglesmm/gogglesmm#76]
I've noticed this after updating to MX-17 with a fresh install over MX-16. It occurs on three different machines each with at least 2G memory all 64 bit. Not a big issue as I can edit with Ex Falso just more convenient to accomplish edits with out changing programs. Thank you for this great music manager.

**Comment by gogglesguy** [comment]
Can you identify what part is slow, just editing the fields in the dialog, saving the changes in the database or saving the changes back to the files? You can disable saving changes to the files to see if it is database related or taglib related. Perhaps it's related to an update to either sqlite or taglib. 

Either way, 0.12.7 is very old and won't received any bugfixes. I would encourage you to update to the latest stable version.

**Comment by ejsant** [comment]
Thank you, the machines freeze when I right click on a track and the choose
"edit" in the menu. 0.12.7 ships with MX-17. I look to update to a more
current stable version and if successful I'll let you know if the issue
resolves. Either way thank you for such a great manager. I use it when
airing my radio show.

Peace,
Ed

Peace, a brilliant aspiration!
