### ISSUE TITLE
Failing to register with last.fm with "token expired"

### ISSUE THREAD

**Issue by phunni** [gogglesmm/gogglesmm#77]
Tried to set up scrobbling to last.fm.  When I played my first track a browser window opened up asking if I was happy with Gogglesmm accessing my account, when I said I was it showed an error saying something along the lines of token expired.

I also can't figure out how to make Gogglesmm try again... I've tried disabling scrobbling and then re-enabling it, but that doesn't seem to do it...

**Comment by gogglesguy** [comment]
I can reproduce this. Looks like a possible bug.
