### ISSUE TITLE
FOX dynamic linking support

### ISSUE THREAD

**Issue by nerijus** [gogglesmm/gogglesmm#81]
1.2.0 changelog: A copy of FOX is now included to make it easier to distribute gogglesmm.
Is it possible to compile with system installed FOX, i.e. not link statically?

**Comment by gogglesguy** [comment]
Yes, you can configure with:

cmake -DWITH_CFOX=OFF 

Keep in mind, this will not be officially supported.

**Comment by nerijus** [comment]
Thank you, this works.
