### ISSUE TITLE
Cyrillic encoding problem in songs that are played

### ISSUE THREAD

**Issue by Bitkeen** [gogglesmm/gogglesmm#82]
![gogglesmm-bug](https://user-images.githubusercontent.com/31455852/42418217-3b247c7c-82a4-11e8-8593-283a4c24c0ed.png)

**Comment by gogglesguy** [comment]
So the text is displayed fine if it's not playing? This may just be the case that the selected font may not have an italic / bold variant. Try switching to a different font in the gogglesmm preferences panel (like DejaVu Sans). What font are you currently using?

**Comment by Bitkeen** [comment]
You are right, I didn't think about the font. The font was Source Sans Variable. Everything is displayed fine with DejaVu Sans.

**Comment by gogglesguy** [comment]
Excellent, it is unfortunate that the UI toolkit used by gogglesmm doesn't have any fancy font rendering to handle these issues automatically
