### ISSUE TITLE
Resuming from pause starts track from beginning

### ISSUE THREAD

**Issue by kaoneko** [gogglesmm/gogglesmm#83]
Recently I found I cannot pause a song anymore. There is no pause button, but I guess it used to work by clicking the play button or pressing ctrl+p, because that's what I intuitively do when I want to pause playback.

Diving into this issue here's what I also found:
- Hitting ctrl+p or clicking the play button during playback seems to actually pause playback: opposed to clicking the stop button, the progress bar remains intact and in the current playing position. The play button doesn't change into a pause button though. When trying to resume playback by ctrl+p or play button, the track starts playing from the beginning.
- This same behaviour is observed when issuing `gogglesmm --pause` and then `gogglessmm --play`, or when issuing `gogglesmm --play-pause` twice.

Maybe this is a regression caused by fdadd8302364d5ef5a579f1737c823cf820ed952? Just a wild guess because the related issue is also about play/pause functionality.

I see that `can_unpause()` used to return `true` when player is pausing, now it returns `player->playing()` which I cannot find (I don't know C++ and don't know what this syntax `abc->def()` means), but I imagine it's a method/function stored in a different class/object or whatever the terminology is in C++ that returns a boolean, so it would return `false` when it is pausing (not playing)?

I'm running v1.2.0 on Ubuntu 16.04.4.

**Comment by gogglesguy** [comment]
Thank you for your report. That was indeed accidentally broken, but should now be fixed.
