### ISSUE TITLE
gentoo package using CFOX=OFF

### ISSUE THREAD

**Issue by zx2c4** [gogglesmm/gogglesmm#86]
I committed this today: https://github.com/gentoo/gentoo/commit/06d861e961112fff54418e37e4083834009dc8dd

Of note is that I'm setting CFOX=OFF, as Gentoo generally prefers to use system libs.

Is that fine, or have you significantly altered Fox, and so things will expode?

**Comment by gogglesguy** [comment]
Thanks! If the text input works in the app you should be fine.

**Comment by zx2c4** [comment]
Great.
