### ISSUE TITLE
HiLite track, Right-click, 'Edit...': CPU/mem spike, then app crash

### ISSUE THREAD

**Issue by ssepan2** [gogglesmm/gogglesmm#89]
Highlight a track, right-click, choose 'Edit...' from the popup menu:

1 CPU immediately goes to 100%, memory climbs for about 10 seconds until 100% (8GB), then swap begins to climb. At about 33% the other 3 CPUs spike to 100%. When swap file maxes out after about 20 seconds (12GB), system becomes unresponsive for about a minute. The app window and process quits. At no time does any Edit dialog appear.
v0.12.7
________________
System specs below. 

[code]
System:    Host: ssepandesktop2 Kernel: 4.15.0-69-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.2.4 wm: muffin dm: LightDM Distro: Linux Mint 19.2 Tina 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Desktop System: Dell product: OptiPlex 7020 v: 00 serial: <filter> Chassis: 
           type: 6 serial: <filter> 
           Mobo: Dell model: 0F5C5X v: A00 serial: <filter> BIOS: Dell v: A10 date: 09/22/2016 
Battery:   Device-1: hidpp_battery_0 model: Logitech M570 serial: <filter> charge: 70% 
           status: Discharging 
CPU:       Topology: Quad Core model: Intel Core i5-4590 bits: 64 type: MCP arch: Haswell rev: 3 
           L2 cache: 6144 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 26338 
           Speed: 1995 MHz min/max: 800/3700 MHz Core speeds (MHz): 1: 1796 2: 1796 3: 1796 
           4: 1796 
Graphics:  Device-1: NVIDIA GK208B [GeForce GT 720] vendor: eVga.com. driver: nouveau v: kernel 
           bus ID: 01:00.0 chip ID: 10de:1288 
           Display: x11 server: X.Org 1.19.6 driver: nouveau unloaded: fbdev,modesetting,vesa 
           resolution: 3840x2160~30Hz 
           OpenGL: renderer: NV106 v: 4.3 Mesa 19.0.8 direct render: Yes 
Audio:     Device-1: Intel 8 Series/C220 Series High Definition Audio vendor: Dell 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:8c20 
           Device-2: NVIDIA GK208 HDMI/DP Audio vendor: eVga.com. driver: snd_hda_intel v: kernel 
           bus ID: 01:00.1 chip ID: 10de:0e0f 
           Sound Server: ALSA v: k4.15.0-69-generic 
Network:   Device-1: Intel Ethernet I217-LM vendor: Dell driver: e1000e v: 3.2.6-k port: f040 
           bus ID: 00:19.0 chip ID: 8086:153a 
           IF: eno1 state: up speed: 100 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 1.93 TiB used: 1002.72 GiB (50.8%) 
           ID-1: /dev/sda vendor: Seagate model: ST1000DM003-1SB102 size: 931.51 GiB 
           speed: 6.0 Gb/s serial: <filter> 
           ID-2: /dev/sdb vendor: Samsung model: SSD 840 EVO 120GB size: 111.79 GiB 
           speed: 6.0 Gb/s serial: <filter> 
           ID-3: /dev/sdc type: USB vendor: Western Digital model: WD My Passport 25E1 
           size: 931.48 GiB speed: 6.0 Gb/s serial: <filter> 
Partition: ID-1: / size: 109.53 GiB used: 52.87 GiB (48.3%) fs: ext4 dev: /dev/sdb1 
           ID-2: /home size: 915.89 GiB used: 447.46 GiB (48.9%) fs: ext4 dev: /dev/sda1 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 3 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 1-1:2 info: Intel ports: 6 rev: 2.0 chip ID: 8087:8008 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 3 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 2-1:2 info: Intel ports: 8 rev: 2.0 chip ID: 8087:8000 
           Hub: 3-0:1 info: Full speed (or root) Hub ports: 15 rev: 2.0 chip ID: 1d6b:0002 
           Device-1: 3-3:2 info: N/A type: Mass Storage driver: usb-storage rev: 2.0 
           chip ID: 3207:0300 
           Device-2: 3-9:3 info: Logitech Unifying Receiver type: Keyboard,Mouse,HID 
           driver: logitech-djreceiver,usbhid rev: 2.0 chip ID: 046d:c52b 
           Hub: 4-0:1 info: Full speed (or root) Hub ports: 6 rev: 3.0 chip ID: 1d6b:0003 
           Device-3: 4-1:2 info: Western Digital type: Mass Storage driver: usb-storage rev: 3.1 
           chip ID: 1058:25e1 
Sensors:   System Temperatures: cpu: 29.8 C mobo: 27.8 C gpu: nouveau temp: 40 C 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/gambas-team-gambas3-bionic.list 
           1: deb http: //ppa.launchpad.net/gambas-team/gambas3/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/microsoft-prod.list 
           1: deb [arch=amd64] https: //packages.microsoft.com/ubuntu/18.04/prod bionic main
           Active apt repos in: /etc/apt/sources.list.d/mono-official-vs.list 
           1: deb https: //download.mono-project.com/repo/ubuntu vs-bionic main
           Active apt repos in: /etc/apt/sources.list.d/mozillateam-ppa-bionic.list 
           1: deb http: //ppa.launchpad.net/mozillateam/ppa/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/noobslab-themes-bionic.list 
           1: deb http: //ppa.launchpad.net/noobslab/themes/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/notepadqq-team-notepadqq-bionic.list 
           1: deb http: //ppa.launchpad.net/notepadqq-team/notepadqq/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com tina main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ bionic partner
           Active apt repos in: /etc/apt/sources.list.d/pmjdebruijn-darktable-release-bionic.list 
           1: deb http: //ppa.launchpad.net/pmjdebruijn/darktable-release/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/vscode.list 
           1: deb [arch=amd64] http: //packages.microsoft.com/repos/vscode stable main
Info:      Processes: 224 Uptime: 6h 12m Memory: 7.73 GiB used: 1.78 GiB (23.0%) Init: systemd 
           v: 237 runlevel: 5 Compilers: gcc: 7.4.0 alt: 7 Client: Unknown python3.6 client 
           inxi: 3.0.32 
[/code]

_______________
Also reproduced on 2nd system  

[code]
System:    Host: edsepanpc Kernel: 5.0.0-35-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.2.4 wm: muffin dm: LightDM Distro: Linux Mint 19.2 Tina 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Desktop System: eMachines product: ET1831 v: N/A serial: <filter> Chassis: 
           type: 3 serial: <filter> 
           Mobo: eMachines model: EMCP73VT-PM serial: <filter> BIOS: AMI v: P01-A0 
           date: 08/21/2009 
CPU:       Topology: Dual Core model: Pentium E5300 bits: 64 type: MCP arch: Penryn rev: A 
           L2 cache: 2048 KiB 
           flags: lm nx pae sse sse2 sse3 ssse3 vmx bogomips: 10400 
           Speed: 1274 MHz min/max: 1203/2603 MHz Core speeds (MHz): 1: 1398 2: 1212 
Graphics:  Device-1: AMD RV730 PRO [Radeon HD 4650] vendor: VISIONTEK driver: radeon v: kernel 
           bus ID: 02:00.0 chip ID: 1002:9498 
           Display: x11 server: X.Org 1.19.6 driver: ati,radeon unloaded: fbdev,modesetting,vesa 
           resolution: 1680x1050~60Hz 
           OpenGL: renderer: AMD RV730 (DRM 2.50.0 / 5.0.0-35-generic LLVM 8.0.0) 
           v: 3.3 Mesa 19.0.8 compat-v: 3.0 direct render: Yes 
Audio:     Device-1: NVIDIA MCP73 High Definition Audio vendor: Acer Incorporated ALI 
           driver: snd_hda_intel v: kernel bus ID: 00:09.0 chip ID: 10de:07fc 
           Device-2: AMD RV710/730 HDMI Audio [Radeon HD 4000 series] vendor: VISIONTEK 
           driver: snd_hda_intel v: kernel bus ID: 02:00.1 chip ID: 1002:aa38 
           Sound Server: ALSA v: k5.0.0-35-generic 
Network:   Device-1: Realtek RTL810xE PCI Express Fast Ethernet vendor: Acer Incorporated ALI 
           driver: r8169 v: kernel port: e800 bus ID: 04:00.0 chip ID: 10ec:8136 
           IF: enp4s0 state: up speed: 100 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 577.51 GiB used: 46.67 GiB (8.1%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 840 EVO 120GB size: 111.79 GiB 
           speed: 3.0 Gb/s serial: <filter> 
           ID-2: /dev/sdb vendor: Seagate model: ST3250820AS size: 232.83 GiB speed: 3.0 Gb/s 
           serial: <filter> 
           ID-3: /dev/sdc vendor: Samsung model: SSD 840 EVO 250GB size: 232.89 GiB 
           speed: 3.0 Gb/s serial: <filter> 
Partition: ID-1: / size: 109.53 GiB used: 29.31 GiB (26.8%) fs: ext4 dev: /dev/sda1 
           ID-2: /home size: 228.23 GiB used: 8.58 GiB (3.8%) fs: ext4 dev: /dev/sdc1 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 8 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 1-7:5 info: Genesys Logic Hub ports: 4 rev: 2.0 chip ID: 05e3:0608 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 8 rev: 1.1 chip ID: 1d6b:0001 
           Device-1: 2-3:2 info: Microsoft Natural Keyboard Elite type: Keyboard 
           driver: hid-generic,usbhid rev: 2.0 chip ID: 045e:000b 
           Device-2: 2-4:3 info: Chic Browser Mouse type: Mouse driver: hid-generic,usbhid 
           rev: 1.0 chip ID: 05fe:0011 
           Device-3: 2-6:4 info: Transcend Information 63-in-1 Multi-Card Reader/Writer 
           type: Mass Storage driver: usb-storage rev: 2.0 chip ID: 1307:0330 
Sensors:   System Temperatures: cpu: 44.0 C mobo: N/A gpu: radeon temp: 68 C 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/mozillateam-ppa-bionic.list 
           1: deb http: //ppa.launchpad.net/mozillateam/ppa/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/notepadqq-team-notepadqq-bionic.list 
           1: deb http: //ppa.launchpad.net/notepadqq-team/notepadqq/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com tina main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ bionic partner
Info:      Processes: 186 Uptime: 1h 32m Memory: 3.85 GiB used: 1.14 GiB (29.6%) Init: systemd 
           v: 237 runlevel: 5 Compilers: gcc: 7.4.0 alt: 7 Client: Unknown python3.6 client 
           inxi: 3.0.32 
[/code]

**Comment by gogglesguy** [comment]
Thanks for your report.  v0.12.7 is a very old release I no longer support. I invite you to install the latest version from my official ppa https://launchpad.net/~s.jansen/+archive/ubuntu/gogglesmm
If the issue still occurs in the latest version, I'm happy to take a look.

**Comment by ssepan2** [comment]
Sander Jansen,
Thank You. You know, the lone review in the (Mint) Software Manager mentions the new PPA, and I overlooked it.
The new version (v1.2.1) is installed, and does not have the issue any more. The issue can be closed.
Thanks Again,
Steve

**Comment by sanderjansen** [comment]
Great!

**Comment by gogglesguy** [comment]
Great!
