### ISSUE TITLE
Keeps clearing settings after closing

### ISSUE THREAD

**Issue by qwaga** [gogglesmm/gogglesmm#91]
I am running Goggles Music Manager on Manjaro Linux. I have to re-apply all the settings I use each time I reboot my computer. I am almost sure that it has nothing to do with my computer. Even an ability to save the settings so I could just enter a file each time would be enough for me.

**Comment by gogglesguy** [comment]
Which version?
Are there any recently written files in ~/.config/gogglesmm and ~/.cache/gogglesmm? 
I assume the database itself loads fine?

**Comment by qwaga** [comment]
> Which version?
> Are there any recently written files in ~/.config/gogglesmm and ~/.cache/gogglesmm?
> I assume the database itself loads fine?

Ah, didn't see this comment until now. It magically fixed itself somehow. Probably was something on my end considering I did not try anything to fix it.
