### ISSUE TITLE
Sndio support

### ISSUE THREAD

**Issue by jarbowski** [gogglesmm/gogglesmm#92]
hi,
it would be nice to have a sndio backend, it's a very good alternative to pulseaudio
thanks

**Comment by gogglesguy** [comment]
Seems pretty esoteric. Are people actually using this? Some basic functionally looks to be absent, it only offers `drain` functionality (stop playback after buffer is clear), no `flushing` behaviour (stop playback right now).

**Comment by jarbowski** [comment]
it's definitely not esoteric, it's available for all *nix
several well known apps have backends:
vlc, mpv, lmms, cmus, musikcube, firefox, sox, gst plugins (with patch, so a lot of apps)
only my favorite app is missing

**Comment by gogglesguy** [comment]
Would you be able to give https://github.com/gogglesmm/gogglesmm/tree/feature-sndio a test drive?

**Comment by jarbowski** [comment]
I've just installed it on an up to date void linux x86_64 and everything is okay, it works smoothly with gapless. It is well recognized and mixed by aucatctl. Thanks a lot

**Comment by jarbowski** [comment]
in fact, it's not that okay
I found that when a track is paused and you launch another one it totally freezes (commit
cfda4cd from feature-sndio branch)

**Comment by gogglesguy** [comment]
Thanks. Last commit https://github.com/gogglesmm/gogglesmm/pull/93/commits/4df1f15719031d1bf62fea40fbda3ad2f9647a57 should have fixed these.

**Comment by jarbowski** [comment]
indeed, it's fixed

**Comment by gogglesguy** [comment]
Available 1.2.2

**Comment by jarbowski** [comment]
Cool,
Thank you
