### ISSUE TITLE
miniplayer customization

### ISSUE THREAD

**Issue by mrfricks** [gogglesmm/gogglesmm#95]
hi, i would like to alter the size some items of the mini player . i have a 4k screen and would like to increase the size of the cover and icons.

where abouts in the source code is the miniplayer defined?

**Comment by gogglesguy** [comment]
Miniplayer code is in https://github.com/gogglesmm/gogglesmm/blob/master/src/GMRemote.cpp
To change the cover size, you'll probably have to adjust the hardwired 64 size in the code itself. To change icon sizes, you can try adding this to ~/.config/gogglesmm/settings.rc

```
[user-interface]
icon-theme-small-size=32

```
Any external icon theme will then be loaded with specific size. 
See https://github.com/gogglesmm/gogglesmm/blob/19902e7be38d7b97e1c60f56a5a3c12beb150a8d/src/GMIconTheme.cpp#L246-L248

To change the size of the builtin standard theme, you would have to manually replace all the files included with gogglesmm.

**Comment by mrfricks** [comment]
thank you! by altering GMIconTheme.cpp i now have a bigger cover image & text in the mini player.
icon-theme-small-size=32 has also worked. i missed the select icons setting in the preferences!
cheers
