### ISSUE TITLE
1.2.1 build fails on openSUSE linux

### ISSUE THREAD

**Issue by lgbaldoni** [gogglesmm/gogglesmm#97]
See attached [log](https://github.com/gogglesmm/gogglesmm/files/4731907/gogglesmm_121.txt).
.

**Comment by gogglesguy** [comment]
Can you attach the complete build log (not just the linking phase) ?

**Comment by gogglesguy** [comment]
oh I see, you're trying to build with BUILD_SHARED_LIBS=ON. That's not supported.

**Comment by lgbaldoni** [comment]
`-DBUILD_SHARED_LIBS=OFF` did the trick, TYVM.
