### ISSUE TITLE
Should cover/lyrics view remember its size ?

### ISSUE THREAD

**Issue by Fenveireth** [gogglesmm/gogglesmm#98]
The splitter on the left panel, between 'Sources' and Artwork of currently playing track, resets itself to center at each start

Which bugs me out more that it should, really, I feel strongly compelled to enlarge the artwork again every time to be *exactly* back on the layout I had on foobar2000 for years and make everything feel right again

I've patched it in for myself, but I feel this reset could be oversight ? All the other controls seem to retain their layout across runs

**Comment by gogglesguy** [comment]
Yes, I can see how that's a bit annoying.

**Comment by gogglesguy** [comment]
Fixed in 1.2.2
